# Generated by Django 3.2.5 on 2021-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerelease',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
