# Generated by Django 3.2.5 on 2021-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_packagerelease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerelease',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagerelease',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
