# Generated by Django 3.2.5 on 2021-08-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210822_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerelease',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagerelease',
            name='version',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
